name: Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]
        project: [bluengo-prueba-jvs]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.5

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Verify Go module
        run: |
          cd ${{ matrix.project }}
          go mod tidy
          go mod download

      - name: Build
        run: |
          OUTPUT_DIR=$GITHUB_WORKSPACE/bin/${{ matrix.project }}_${{ matrix.goos }}_${{ matrix.goarch }}
          mkdir -p $OUTPUT_DIR
          cd ${{ matrix.project }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $OUTPUT_DIR/app main.go
          echo "Archivos generados:"
          ls -lah $OUTPUT_DIR

      - name: Zip executable
        run: |
          OUTPUT_DIR=$GITHUB_WORKSPACE/bin/${{ matrix.project }}_${{ matrix.goos }}_${{ matrix.goarch }}
          ZIP_NAME=app_${{ matrix.project }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
          
          if [ ! -f "$OUTPUT_DIR/app" ]; then
            echo "Error: El binario no fue generado correctamente."
            exit 1
          fi

          cd $OUTPUT_DIR
          zip -j $ZIP_NAME app
          mv $ZIP_NAME $GITHUB_WORKSPACE/bin/

      - name: Verify ZIP file
        run: |
          ZIP_PATH=$GITHUB_WORKSPACE/bin/app_${{ matrix.project }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
          if [ -f "$ZIP_PATH" ]; then
            echo "El archivo ZIP se creó correctamente: $ZIP_PATH"
          else
            echo "Error: El archivo ZIP no se creó correctamente."
            exit 1
          fi

      - name: List ZIP files
        run: |
          echo "Listando archivos ZIP:"
          ls -lah $GITHUB_WORKSPACE/bin/

      - name: Upload artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: app_${{ matrix.project }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
          path: bin/app_${{ matrix.project }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip

  release:
    needs: build  # Dependiendo de si necesitas la salida del job 'build'
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el código
        uses: actions/checkout@v4

      - name: Descargar los artefactos del build
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Crear Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/app_bluengo-prueba-jvs_darwin_amd64.zip
            artifacts/app_bluengo-prueba-jvs_darwin_arm64.zip
            artifacts/app_bluengo-prueba-jvs_linux_amd64.zip
            artifacts/app_bluengo-prueba-jvs_linux_arm64.zip
            artifacts/app_bluengo-prueba-jvs_windows_amd64.zip
            artifacts/app_bluengo-prueba-jvs_windows_arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

